version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      context: ./.env
      DB_HOST: host.docker.internal
    ports:
      - 4000:4000

  db-postgres:
    image: postgres
    restart:
    environment:
      context: ./.postgres.env
      DB_HOST: host.docker.internal
    volumes:
      - ./data/postgres:/var/lib/postgresql
    ports:
      - 5433:5432
    expose:
      - 5432

  cache:
    image: redis:6.2-alpine
    restart: always
    environment:
      context: ./.redis.env
      DB_HOST: host.docker.internal
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
